services:
  postgres:
    image: postgres:17
    container_name: pg17-json
    environment:
      POSTGRES_PASSWORD: manager
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
